service:
  port: 8091
  shutdownGraceDuration: 1s

database:
  type: memory
  server: localhost:27017
  dbname: MessageManager
  username: root
  password: example
  timeout: 10s

logging:
  level: debug
