service:
  port: 8091
  shutdownGraceDuration: 10

database:
  type: mongo
  server: localhost:27017
  dbname: MessageManager
  username: root
  password: example
  timeout: 10

logging:
  level: debug
