service:
  port: 8090
  healthPort: 8091
  healthScanInterval: 30s
  shutdownGraceDuration: 1s

database:
  type: mongo
  server: mongo:27017
  dbname: MessageManager
  username: root
  password: example
  timeout: 10s

logging:
  level: debug
